import type { Metadata } from "next";
import {IBM_Plex_Sans,Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";


const inter=Inter({
  subsets:["latin"],
  weight:["100","200","300","400","500","600","700","800","900"],
  variable:"--font-inter"
})
const ibmplexsans=IBM_Plex_Sans({
  subsets:["latin"],
  weight:["100","200","300","400","500","600","700"],
  variable:"--font-ibmplexsans"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${inter.className} ${ibmplexsans.variable} ${ibmplexsans.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-neutral-100 dark:bg-neutral-700">
        <Header/>
        {children}
        </body>
    </html>
  );
}
